### ISSUE TITLE
CRAFT PyTorch for time series

### ISSUE THREAD

**Issue by ansariyusuf** [deel-ai/xplique#158]
I have time series ECG data. Can I use Pytorch CRAFT to visualize concepts in my 12-channel ECG data?

**Comment by AntoninPoche** [comment]
Dear @ansariyusuf,

The CRAFT method was designed for images and have never have been applied to Time Series to my knowledge. Furthermore, our implementation only supports images.

You might be able to make the method run for if you treat your Time Series as a one channel image but I would not recommend it. Indeed, you might be able to make the decomposition into concepts, but the visualization and interpretation of such concepts will not be possible.

Best regards

**Comment by ansariyusuf** [comment]
Hi,

I am able to generate the concepts and view the patches that correspond to these concepts. Why is the visualization and interpretation of these not possible? Can't the patches that correspond to these concepts be overlayed on the original signal to which the patch belongs?

I would really appreciate your guidance on this issue.

**Comment by AntoninPoche** [comment]
Dear @ansariyusuf,

First, I am not sure what you did exactly; thus, I will suppose the following:
- You have time series samples of shape (n, t, w).
- You treat them as one-channel images (n, h, w, 1).
- You apply CRAFT decomposition and obtain concepts.

At this point, you have a first problem with the `fit` method from CRAFT extract patches as shown in [line 246 from `xplique/concepts/craft.py`](https://github.com/deel-ai/xplique/blob/8da7ef16ec20a39fbda4688fc962ab13b3c06b1c/xplique/concepts/craft.py#L246).

However, patches are defined as crops from images. Crops from images can be resized and considered a new valid input image. But, to my knowledge, you cannot do that for time series. We must keep in mind that the implement method is designed for images and that all manipulations were done by supposing we have an image. Furthermore, such automatic concept extraction for time series methods belongs to the research domain. Therefore, research, experiments, definition, and such should be done before using CRAFT for time series.

Nonetheless, I can try to give you some insights on the problems linked with applying CRAFT on time series:
- First, no matter what you try, the `patch_size` should be set to w, the number of features in your time series. Otherwise, a resize would be done from some features to others, and values would not make sense.
- Now, as patches are squares (at least in our implementation), the time dimension in the time series will be cropped by `patch_size` and then resized to t (the number of time steps in your windows). This means that we manually change the frequency of the input provided to the model. If the model has never seen time series with this frequency, resized patches would be completely out of distribution; therefore, the concepts extracted from such patches do not make sense.

I hope I shedded light on why CRAFT should not be applied as such to a time series.

Best regards,
Antonin

**Comment by ansariyusuf** [comment]
Hi thank you for sharing this. I understand the concern you have raised with patches. For the case of images as well, the model is not trained with the crops/patches of the images rather complete images. So there is an inherent difference in the distribution of the copped patches which are resized as compared to the data model is trained on. Is my understanding correct?

I am greatful to you for taking out to time to answer to my queries.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AntoninPoche** [comment]
Dear @ansariyusuf,

From my comprehension of computer visions, images can be of varying qualities and more or less zoomed. Furthermore, images receive huge data augmentation, crop and resize being common.

Therefore, my understanding is that such resized patches can be considered in the distribution or at least close to the distribution seen by the vision model during training.

Best regards,
Antonin

**Comment by ansariyusuf** [comment]
Thank you for these insights. I will keep these in mind when working with my data.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AntoninPoche** [comment]
You are welcome; thank you for your interest in our library!
